### ISSUE TITLE
Chrome console error

### ISSUE THREAD

**Issue by itskawsar** [jekkos/opensourcepos#1191]
When i'm running on google chrome getting following error but the app is running fine:

```
Error in event handler for (unknown): SyntaxError: Failed to execute 'addRule' on 'CSSStyleSheet': Failed to parse the rule '::content #weblink_ads_container, ::content .Ad160x600, ::content .FeaturedAdIndexAd, ::content .TopAd, ::content .ad-Leaderboard, ::content .ad-fullbanner-btf-container, ::content .ad-unit-medium-retangle, ::content .ad728_wrap, ::content .adInNews, ::content .adWrapLg, ::content .ad_center_bottom, ::content .ad_perma-panorama, ::content .adblock-wide, ::content .adlayer, ::content .ads-leaderboard-panel, ::content .adsTopCont, ::content .adsbox-square, ::content .adsmalltext, ::content .adv336, ::content .advert-wrap2, ::content .advertisementFull, ::content .adx-300x600-container, ::content .b-ad, ::content .big-right-ad, ::content .bodyads, ::content .cns-ads-stage, ::content .custom_banner_ad, ::content .e-ad, ::content .footer_bottom_ad, ::content .google-ad-space-vertical, ::content .h-ad-remove, ::content .homepage-ad-block-padding, ::content .inlinead-tagtop, ::content .lead-board-ad-cont-home, ::content .mainAdContainer, ::content .mod-ad-lrec, ::content .nc-dealsaver-container, ::content .pan-ad-inline3, ::content .premium-ad, ::content .remove-ads, ::content .rr-300x250-ad, ::content .sideBoxMiddleAd, ::content .sl_ad5, ::content .sponsored-links-tbl, ::content .stream-ad, ::content .tileAdWrap, ::content .tower-ads-container, ::content .w-ad-box, ::content .wpx_bannerize, ::content a[href^="http://campaign.bharatmatrimony.com/track/"], ::content a[href^="http://www.pinkvisualgames.com/?revid="], ::content .GKJYXHBF2 > .GKJYXHBE2 > .GKJYXHBH5, ::content #AD_CONTROL_8, ::content #Ads_google_05, ::content #HorizontalAd, ::content #\5f _mom_ad_2, ::content #ad-circfooter, ::content #ad-right-sidebar-ad-2, ::content #ad32, ::content #adMagAd, ::content #adZoneTop, ::content #ad_channel, ::content #ad_panorama_top, ::content #adbanner00005, ::content #adlink-197, ::content #ads160_600-widget-3, ::content #ads_top_container, ::content #adspot-1, ::content #adv_Inread, ::content #advertisementFooterTop, ::content #amazon-ads, ::content #banner_adv, ::content #bn_ad, ::content #caAdLarger, ::content #db_ad, ::content #div-web-ad-content-article, ::content #first_ad, ::content #gm-ad-lrec, ::content #header-ad2, ::content #hp-store-ad, ::content .abp_ob_exist, ::content #ad_box300x250, ::content .ad_stream, ::content .ad-box-adsea, ::content .ad_panel_2, ::content .specialHeaderAd, ::content .js-billboard-advert, ::content #ad_panel_1, ::content .ad_label_centered, ::content a[href^="http://farm.plista.com/pets"], ::content .c-ad-size3, ::content .literatumAd, ::content #adserver_HeaderAd, ::content .billboard__advert, ::content .ad_box300x250, ::content #ad_panel_2, ::content #adv-scrollable, ::content .sponsored_bar_text, ::content .header-ad-frame, ::content a[href^="https://farm.plista.com/pets"], ::content .adLat, ::content .ad728x90-main_wrap, ::content .c-ad, ::content .ad_panel_1, ::content a[href^="https://understandsolar.com/signup/?lead_source="][href*=&tracking_code="], ::content #desktop-unrec-ad, ::content .pb-ad, ::content .c-ad-size2, ::content .adsBlock, ::content .adv-border, ::content .bannerad, ::content .rectangle_ad, ::content .top_ads, ::content a[href^="http://ad-emea.doubleclick.net/"], ::content td[valign="top"] > .mainmenu[style="padding:10px 0 0 0 !important;"], ::content #homead, ::content .ad-leaderboard, ::content .ad-slot, ::content .adResult, ::content .ads-1, ::content .ads_google, ::content .adtile, ::content .ob_container .item-container-obpd, ::content .td-adspot-title, ::content #adunit, ::content #download_ad, ::content #sponsoredwellcontainerbottom, ::content .ad_default, ::content .bxad, ::content .panel-ad, ::content #adblock2, ::content #bottom-ads-container, ::content .AD_area, ::content .adHeaderblack, ::content .reklama1, ::content #adLayer, ::content #topBannerAd, ::content .banner_ad, ::content .pm-ad-zone, ::content #ad_leaderboard, ::content .ac_adbox, ::content .container_row_ad, ::content .ezAdsense, ::content .item-container-ad, ::content .zergnetBLock, ::content #BottomAds, ::content #ad_728_90, ::content .ad-head, ::content .ad_160, ::content .adbottom, ::content .admain, ::content .ads_300, ::content #center-ad, ::content #sponsorText, ::content .side-ad, ::content .static-ad, ::content a[href^="http://ads.betfair.com/redirect.aspx?"], ::content #ad-bg, ::content #adText, ::content .article-ad-bottom, ::content a[href*=".trust.zone"], ::content #ad-728, ::content #rightAds, ::content .ad-s-rendered, ::content .ads-title, ::content .banner-ad, ::content .top-ad-wrapper, ::content a[href^="https://www.dsct1.com/"], ::content #zergnet, ::content #adBanner, ::content #div_prerollAd_1, ::content .ads-label, ::content .wppaszone, ::content #ad-right, ::content #top_ad, ::content #videoAd, ::content .advert-box, ::content .article_ad, ::content .single_ad, ::content #content-header-ad, ::content #dfp_ad_Home_728x90, ::content .header_ad_center, ::content .mediumRectangleAd, ::content .sidebar_ad_3, ::content div[id^="dmRosAdWrapper"], ::content #RightAdBlock, ::content .ad-banner, ::content .smallAd, ::content #msad, ::content .SponsoredLinks, ::content .adHead, ::content a[href^="http://adultfriendfinder.com/p/register.cgi?pid="], ::content .ad-2, ::content .top_ad, ::content a[href^="http://track.adform.net/"], ::content #ad-main, ::content .AdTitle, ::content .LoungeAdsBottomLinks, ::content .ad-inserter-widget, ::content .ad_slug_table { display: none !important; }'.
    at addElemHideSelectors (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js:533:19)
    at checkLoaded (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js:559:7)
    at chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js:575:7
    at CSSPropertyFilters.<anonymous> (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/cssProperties.js:132:7)
```
I have tested on Firefox and it is fine.

Thanks.

**Comment by daN4cat** [comment]
Ads are not coming from OSPOS check your hosting service.

**Comment by daN4cat** [comment]
This post looks to me more about spam posting to be honest....

**Comment by daN4cat** [comment]
I cleaned the post from all the suspicious links as that's for sure not an OSPOS issue.

**Comment by itskawsar** [comment]
@daN4cat sorry to say that I am facing this issue and reporting. I don't know why you think this post is spam. :(

**Comment by daN4cat** [comment]
Could you please remove the content? There are links inside to stuff not related to OSPOS. They are ads, if you don't clean it up I would block you. That's spam.

**Comment by daN4cat** [comment]
This conversation is now locked.
