### ISSUE TITLE
frontaccounting integration

### ISSUE THREAD

**Issue by pcrcastro** [jekkos/opensourcepos#971]
Good afternoon jekkos, I follow you a long time ago and I congratulate you for your contribution to the community. I ask if you can collaborate with an aggregate on opensourcepos. I need to integrate sales to a free erp (frontaccounnting). Best Regards Cesar

**Comment by alvin101** [comment]
@pcrcastro I have not much time today, but I would also like this, I have some links and info to share.

We will need a coder to help with this, and maybe a little seed money.

More later

**Comment by pcrcastro** [comment]
perfect when you have time, whether I agree he is the budget to begin with. regards Cesar


________________________________
De: Alvin <notifications@github.com>
Enviado: lunes, 14 de noviembre de 2016 10:20 a.m.
Para: jekkos/opensourcepos
Cc: pcrcastro; Mention
Asunto: Re: [jekkos/opensourcepos] frontaccounting integration (#971)


@pcrcastro<https://github.com/pcrcastro> I have not much time today, but I would also like this, I have some links and info to share.

We will need a coder to help with this, and maybe a little seed money.

More later

-

**Comment by layoutng** [comment]
hello
pls i am a student. i am interested in the ospos integration with FA

**Comment by SteveIreland** [comment]
I too am interested.  What's the general impression of FrontAccounting?  Is someone that is using OSPOS also using FrontAccounting?  I might be easily talked into providing an integration from OPSPOS into FrontAccounting for the purpose of A/R, Purchasing, and Accounts Payable tracking.  But I'd like to make sure that it is a viable alternative to QuickBooks.   Thoughts and Opinions?

**Comment by pcrcastro** [comment]
Hi,

I do not understand your mail,

I needed that integration a long time ago, but the project closed due to lack of funding.

excuse me,

Besto Regards, Cesar

________________________________
De: layoutng <notifications@github.com>
Enviado: miércoles, 12 de julio de 2017 07:40 p.m.
Para: jekkos/opensourcepos
Cc: pcrcastro; Mention
Asunto: Re: [jekkos/opensourcepos] frontaccounting integration (#971)


hello
pls i am a student. i am interested in the ospos integration with FA

**Comment by pcrcastro** [comment]
Hi,


I do not understand your mail,


I needed that integration a long time ago, but the project closed due to lack of funding.


excuse me, best regards Cesar


________________________________
De: Steve Ireland <notifications@github.com>
Enviado: miércoles, 12 de julio de 2017 11:57 p.m.
Para: jekkos/opensourcepos
Cc: pcrcastro; Mention
Asunto: Re: [jekkos/opensourcepos] frontaccounting integration (#971)


I too am interested. What's the general impression of FrontAccounting? Is someone that is using OSPOS also using FrontAccounting? I might be easily talked into providing an integration from OPSPOS into FrontAccounting for the purpose of A/R, Purchasing, and Accounts Payable tracking. But I'd like to make sure that it is a viable alternative to QuickBooks. Thoughts and Opinions?

**Comment by SteveIreland** [comment]
Timing is everything.   

I see that you initiated this thread back in November 2016. @daN4cat decided this would be a good enhancement to OSPOS in February 2017, and @layoutng brought this thread to my attention by posting on it.  

I need a back office app for OSPOS for my client.  Funding is not an issue for me, so I will be doing some research on FrontAccounting this weekend.  I'll probably go ahead and install it and explore the database to determine how compatible it is with OSPOS and if the reviews are good and it looks "doable" then I'll move forward with writing the interfaces.

If anyone has any thoughts on how the integration should be put together I'd like to read about it.  So please post them to this thread.

And if @daN4cat still thinks this would be a good addition for release 3.2.0 then we will make it happen.

**Comment by jlctmaster** [comment]
I aim for this contribution, please @SteveIreland  include me during the development phase, as this feature is very requested for this system.

Greetings.

**Comment by daN4cat** [comment]
@SteveIreland first we close 3.1 and then we move to the next.....

**Comment by daN4cat** [comment]
And it can be for 3.2.0, yes

**Comment by SteveIreland** [comment]
Discussed with my client and he agreed to move forward with Front Accounting.  I checked it out and was a bit disappointed that it seems to have some issues with the later version of PHP, but it doesn't seem to be a show stopper. So I'll be moving forward with this.

**Comment by odiea** [comment]
It installs just fine using php 5.6 but will not install using php 7.0.

**Comment by daN4cat** [comment]
Latest version looks to be Php7 compatible, see http://frontaccounting.com/wb3/pages/posts/release-2.4.1216.php

**Comment by odiea** [comment]
I read that too.
![2017-07-15 15_16_53-frontaccounting-2 4 1](https://user-images.githubusercontent.com/10962177/28242739-f1f0d598-6970-11e7-8b9c-29345993fa00.png)
And here is what error I received. I did not get this error installing on php 5.6
Notice: Trying to get property of non-object in C:\xampp\htdocs\frontaccounting\includes\errors.inc on line 74

Fatal error: Uncaught Error: Call to undefined function user_company() in C:\xampp\htdocs\frontaccounting\includes\errors.inc:85 Stack trace: #0 C:\xampp\htdocs\frontaccounting\install\isession.inc(84): error_handler(8192, 'Methods with th...', 'C:\\xampp\\htdocs...', 19, Array) #1 C:\xampp\htdocs\frontaccounting\install\isession.inc(84): include_once() #2 C:\xampp\htdocs\frontaccounting\install\index.php(18): include('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\frontaccounting\includes\errors.inc on line 85

**Comment by odiea** [comment]
This is the error I got from his last 2.3.26 version on php7.
Fatal error: Uncaught Error: Call to undefined function user_company() in C:\xampp\htdocs\frontaccounting\includes\errors.inc:87 Stack trace: #0 C:\xampp\htdocs\frontaccounting\install\isession.inc(72): error_handler(8192, 'Methods with th...', 'C:\\xampp\\htdocs...', 19, Array) #1 C:\xampp\htdocs\frontaccounting\install\isession.inc(72): include_once() #2 C:\xampp\htdocs\frontaccounting\install\index.php(18): include('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\frontaccounting\includes\errors.inc on line 87

**Comment by layoutng** [comment]
me too, I aim for this contribution, please @SteveIreland
<https://github.com/steveireland> include me during the development phase,
as this feature is very requested for this system.
Greetings

**Comment by jekkos** [comment]
Won't we need #615 for this one?

**Comment by SteveIreland** [comment]
We can include the requirements for #615 into this effort.  I don't personally have a requirement for disconnected use of OSPOS, but if that's a common use case then it makes sense to incorporate it.

**Comment by SteveIreland** [comment]
Does anyone using FrontAccounting have any opinions of this module?  Is this something we can use?

http://frontaccounting.com/fawiki/index.php?n=Devel.SimpleAPIModule

**Comment by SteveIreland** [comment]
If found @alvin101 made an inquiry about this module back in November 2016. 

https://github.com/andresamayadiaz/FrontAccountingSimpleAPI/issues/25

Based on that brief inquiry it looks like we could use it for our purposes.

**Comment by daN4cat** [comment]
@SteveIreland the problem with that SimpleAPI is that there is no authentication or security.
At least something needs to be in place.

BTW, I still find FA UI really not that user friendly....

**Comment by SteveIreland** [comment]
I do agree that the FA UI could use a makeover, but as long as it can deliver what it promises functionally then I think everyone should be happy.  I would have loved to develop my own and maybe I still will (after I retire), but this will do.

**Comment by daN4cat** [comment]
I found a bootstrap reskin of FA, but I'm not sure it's been ported to the latest version. That makes the application look better.

**Comment by SteveIreland** [comment]
There is a bit of "old school" security with the API.  It expects the company identifier, user name, and password for each request in the header.

**Comment by daN4cat** [comment]
old stuff....

**Comment by SteveIreland** [comment]
guzzlehttp seems to be a component that will make this effort a bit easier.  Is that something that you will allow to be added as a dependency?  If so do you add it independently or should I make the change to composer.json and include it as part of the pull request?

**Comment by SteveIreland** [comment]
I expect to expand this in steps during the next release.  My personal requirement doesn't require extensive security since I'll be running FrontAccounting and OSPOS on the same box, but since I'd like to see this effort have wider use then I plan on including support for OAuth and JWT as the security framework.

**Comment by daN4cat** [comment]
If we switch to guzzlehttp then we should move all the curl based stuff to that one..... eventually.

**Comment by amrshah** [comment]
Hi,

I was thinking an accounts module into OSPOS would be a great one to do. Then I found #615. Count me in on this one :)

**Comment by daN4cat** [comment]
@amrshah work with @SteveIreland on a common repo to add that connector to OSPOS.

However it would be nice to understand how you plan to do that, when you have an idea.

**Comment by daN4cat** [comment]
@SteveIreland I understand we will park this one. If somebody else fancies this integration, please let us know.

**Comment by SteveIreland** [comment]
Agreed.  I stubbed my toe on this one when I realized that the SimpleAPI module that I was going to take advantage of hadn't been kept up with the FrontAccounting releases.  I was going to revisit after I finished up the purchasing module and we have a debt management module.

**Comment by gouravmalviya0** [comment]
I am also getting this error in FA and I have php 7.1 how to install it instruct me
Fatal error: Uncaught Error: Call to undefined function user_company() in C:\xampp\htdocs\maaksons\includes\errors.inc:86 Stack trace: #0 C:\xampp\htdocs\maaksons\includes\session.inc(376): error_handler(8192, 'Methods with th...', 'C:\\xampp\\htdocs...', 19, Array) #1 C:\xampp\htdocs\maaksons\includes\session.inc(376): include_once() #2 C:\xampp\htdocs\maaksons\index.php(18): include_once('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\maaksons\includes\errors.inc on line 86

**Comment by WebShells** [comment]
@SteveIreland have you tried to move forward with FA ?

**Comment by SteveIreland** [comment]
@WebShells Nope.  When the company I was setting everything up for abandoned OSPOS and left me hanging, there wasn't a good reason for me to spend my time on it.

However, the company wants back in and I've been focusing on upgrading them to the latest release of OSPOS and making sure it will still work or them.  They've gone through a few business transitions themselves but are essentially the same RV Service and Parts store.

It's possible I could come back to it, but I don't see it happening at this time.  It's not something the company is now asking for.
